"""Simulation configuration parameters"""

# World parameters
WORLD_SIZE = (100, 100)
FOOD_DENSITY = 0.1
OBSTACLE_DENSITY = 0.05
SOUND_DECAY_RATE = 0.9
FOOD_SPAWN_RATE = 0.01

# Creature parameters
INITIAL_HEALTH = 100.0
INITIAL_ENERGY = 100.0
INITIAL_ACTION_TOKENS = 10
MAX_ACTION_TOKENS = 50
ENERGY_COST_PER_STEP = 1.0
HEALTH_DECAY_RATE = 0.1

# Mood system parameters
FAST_LEARNING_RATE = 0.1  # For arousal
SLOW_LEARNING_RATE = 0.01  # For valence
AROUSAL_DECAY_RATE = 0.99

# Action selection
ACTION_ACCEPTANCE_RATE = 0.9
LLM_ACTION_PROBABILITY = 0.2  # How often to use LLM if available

# Rewards
SURPRISE_REWARD_MULTIPLIER = 0.5
FOOD_REWARD = 1.0
SOCIAL_SOUND_REWARD = 0.3
COLLISION_PENALTY = -0.2
PROXIMITY_REWARD = 0.1

# Analysis
DEFAULT_ANALYZE_EVERY = 500
SOUND_HISTORY_WINDOW = 50
RHYTHM_DETECTION_THRESHOLD = 0.5